# Generated by Django 4.1.13 on 2023-12-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comission_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
